Added songs list api
astronomersiva/landlord pull request #1
Opened 2017-07-29 16:52 UTC by girdhariag

2017-08-01 16:25 UTC, astronomersiva commented on lib/getsongslist.js
> +        thumbnail: first.pictures.thumbnail,
`pictures.thumbnail` looks too small on desktop Messenger. Can we settle for `pictures.medium_mobile`?

2017-08-01 16:32 UTC, astronomersiva requested changes

2017-08-01 16:32 UTC, astronomersiva commented on lib/getsongslist.js
> +  const keysJoined = keyArray.join('+');
@girdhariag , there is a chance of the keyArray being something like `['sicilian pizza', 'pepperoni']`(returned by Google's Vision API). When you do a `keyArray.join( )`, keysJoined will be `sicilian%20pizza+pepperoni` which doesn't work with our songs API. A quick workaround would be doing something like `keyArray.join('+').replace(' ', '+')`. If you have a better solution for this, that would be awesome as well.

I will merge this PR once this is fixed 👍

2017-08-01 16:32 UTC, astronomersiva commented on lib/getsongslist.js
> +      return song;
Can you change it to return a promise instead? 

`resolve` the song or the empty object below and `reject` in case of err.

2017-08-01 16:56 UTC, girdhariag commented on lib/getsongslist.js
> +        thumbnail: first.pictures.thumbnail,
I am keeping the property key as thumbnail only.

2017-08-01 17:00 UTC, astronomersiva commented on lib/getsongslist.js
> +        thumbnail: first.pictures.thumbnail,
Yeah, no problem with that.

2017-08-02 15:09 UTC, astronomersiva approved these changes
:1st_place_medal:

2017-08-02 15:10 UTC, merged